apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: poo-gitops
  description: This is GitOps manifest for poo   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: poo
    backstage.io/kubernetes-id: poo 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: poo   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:poo
