apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: poo
  janus-idp.io/tekton: poo
  backstage.io/kubernetes-id: poo
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: poo
resources:
- deployment.yaml
- route.yaml
- service.yaml
